"""Add constraints to database

Revision ID: 7140ea1c766b
Revises: 2dbc98d65eda
Create Date: 2023-09-18 19:00:39.504489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7140ea1c766b'
down_revision = '2dbc98d65eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.alter_column('prerequisite',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('responsibilities', schema=None) as batch_op:
        batch_op.alter_column('obligation',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('responsibilities', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('obligation',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('prerequisite',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
