"""new try

Revision ID: f81822175561
Revises: 3bb79b155622
Create Date: 2023-09-14 09:34:25.130043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81822175561'
down_revision = '3bb79b155622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_job_joins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_job_joins', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
